Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu64"

  config.vm.network "private_network", ip: "192.168.37.12"
  config.vm.network "forwarded_port", guest: 8080, host: 1404

  config.vm.provision "puppet"
end
